openapi: "3.0.0"
info:
  title: Case Conflict
  version: "1.0.0"
paths: {}
components:
  schemas:
    alert:
      type: object
      properties:
        labels:
          type: object
    Alert:
      type: object
      properties:
        state:
          type: string
    AlertGroup:
      type: object
      properties:
        alerts:
          type: array
          items:
            $ref: "#/components/schemas/Alert"
